### PR TITLE
Fixed Makefile to include targets when obeying KERNELRELEASE

### PR DESCRIPTION
**Pull request by oscarnyl**
This Pull request intends to make sure that the Makefile is compatible with DKMS, which supplies "KERNELRELEASE" to the Makefile from its "-k"-flag.

Previously when supplied the KERNELRELEASE-variable, the Makefile exited due to lack of targets. After this change the Makefile obeys KERNELRELEASE, and builds properly upon calling "dkms build".

### CODE REVIEW

**Comment by kuba-moo** [comment]
This looks weird. Existing logic is if `KERNELRELEASE` is set make is called from `KBuild`, otherwise invoke `KBuild`. After your change you always invoke KBuild, no? Besides what do you mean by `supplies "KERNELRELEASE" to the Makefile from its "-k"-flag` AFAIK `-k` has nothing to do with variables.

**Comment by oscarnyl** [comment]
I'll admit to being a bit out of my territory, and this might have been more fit to bring up in an issue, but the problem I had while attempting to build from dkms for a kernel not currently running (using "dkms install -m mt7601u -v 3.1 -k 4.0.6-2-ARCH") was that with the existing makefile did not actually do anything ("make: **\* No targets.  Stop."). The command dkms called was "make KERNELRELEASE=4.0.6-2-ARCH", and from what I was able to figure out was that the initial ifeq in the Makefile caused no targets to be exposed (as default, clean and install are all inside the ifeq).

After my change calling the aforementioned dkms-command the module built and installed as expected. If this change causes problems in build methods I have not attempted we should probably take a look at what we can do to make dkms work aswell.

**Comment by kuba-moo** [comment]
Yeah, I'm afraid this would break other build setups.

I pushed a patch to the `testing` branch. Can you see if it fixes your problem?

**Comment by oscarnyl** [comment]
Yes, this appears to fix the problem.

**Pull request closed without merging**
